spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      access-key: LTAI5tFXiqr7RgYAGkh4635k
      secret-key: JVlttk2ABY4DnD6pAIhc5A5Wch9G2m
  application:
    name: cubemall-third-party
server:
  port: 30000